/*CL2006 - DATABASE SYSTEMS - LAB 7 - BAI-4A - 24K-0017*/

-- Lab 7 - START

-- Q1)

-- a)
SELECT e.FIRST_NAME, d.DEPARTMENT_NAME
FROM EMPLOYEES e
INNER JOIN DEPARTMENTS d
ON e.DEPARTMENT_ID = d.DEPARTMENT_ID;

-- b)
SELECT e.FIRST_NAME, j.JOB_TITLE
FROM EMPLOYEES e
CROSS JOIN JOBS j;

-- c)
SELECT e.FIRST_NAME, d.DEPARTMENT_NAME
FROM EMPLOYEES e
LEFT OUTER JOIN DEPARTMENTS d
ON e.DEPARTMENT_ID = d.DEPARTMENT_ID;

-- d)
SELECT e.FIRST_NAME, d.DEPARTMENT_NAME
FROM EMPLOYEES e
LEFT OUTER JOIN DEPARTMENTS d
ON e.DEPARTMENT_ID = d.DEPARTMENT_ID;

-- Q2)

-- a)
SELECT d.DEPARTMENT_NAME, e.FIRST_NAME
FROM EMPLOYEES e
RIGHT OUTER JOIN DEPARTMENTS d
ON e.DEPARTMENT_ID = d.DEPARTMENT_ID;

-- b)
SELECT EMPLOYEE_ID FROM EMPLOYEES
INTERSECT
SELECT EMPLOYEE_ID FROM JOB_HISTORY;

-- c)
SELECT EMPLOYEE_ID FROM EMPLOYEES
MINUS
SELECT EMPLOYEE_ID FROM JOB_HISTORY;

-- Q3)

CREATE VIEW EMP_VIEW AS
SELECT e.FIRST_NAME || ' ' || e.LAST_NAME AS FULL_NAME,
       d.DEPARTMENT_NAME,
       j.JOB_TITLE
FROM EMPLOYEES e
JOIN DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
JOIN JOBS j ON e.JOB_ID = j.JOB_ID;

-- Q4) 

CREATE VIEW EMP_REPORT AS
SELECT e.EMPLOYEE_ID,
       e.FIRST_NAME || ' ' || e.LAST_NAME AS FULL_NAME,
       d.DEPARTMENT_NAME,
       j.JOB_TITLE,
       e.SALARY
FROM EMPLOYEES e
JOIN DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
JOIN JOBS j ON e.JOB_ID = j.JOB_ID
WHERE e.SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES)
ORDER BY e.SALARY DESC;

-- Q5)

-- a)
CREATE VIEW DEPT50_VIEW AS
SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 50
WITH CHECK OPTION;

-- b)
SELECT EMPLOYEE_ID FROM EMPLOYEES
UNION
SELECT EMPLOYEE_ID FROM JOB_HISTORY;

-- Q6)

CREATE VIEW HR_ANALYTICS AS
SELECT e.EMPLOYEE_ID,
       e.FIRST_NAME || ' ' || e.LAST_NAME AS FULL_NAME,
       d.DEPARTMENT_NAME,
       j.JOB_TITLE,
       e.SALARY
FROM EMPLOYEES e
JOIN DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
JOIN JOBS j ON e.JOB_ID = j.JOB_ID
WHERE e.SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES);

-- Q7)

-- a)
CREATE VIEW SECURE_EMP AS
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT_ID, SALARY
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 10
WITH CHECK OPTION;

-- b)
SELECT EMPLOYEE_ID FROM EMPLOYEES
UNION
SELECT EMPLOYEE_ID FROM JOB_HISTORY;

-- Lab 7 - END
