/*CL2006 - DATABASE SYSTEMS - LAB 8 - BAI-4A - 24K-0017*/

-- Lab 8 - START

-- Pre-Lab Tasks)

-- DML)
CREATE TABLE EMPLOYEE_BONUS (
    EMPLOYEE_ID NUMBER,
    BONUS NUMBER
);

CREATE OR REPLACE TRIGGER trg_employee_bonus
AFTER INSERT ON EMPLOYEES
FOR EACH ROW
BEGIN
    INSERT INTO EMPLOYEE_BONUS
    VALUES (:NEW.EMPLOYEE_ID, :NEW.SALARY * 0.10);
END;
/

CREATE OR REPLACE TRIGGER trg_salary_limit
BEFORE UPDATE OF SALARY ON EMPLOYEES
FOR EACH ROW
BEGIN
    IF :NEW.SALARY > 10000 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Salary exceeds allowed limit');
    END IF;
END;
/

CREATE TABLE DELETED_EMP_LOG (
    EMPLOYEE_ID NUMBER,
    FIRST_NAME VARCHAR2(50),
    DELETED_AT DATE
);

CREATE OR REPLACE TRIGGER trg_deleted_emp_log
AFTER DELETE ON EMPLOYEES
FOR EACH ROW
BEGIN
    INSERT INTO DELETED_EMP_LOG
    VALUES (:OLD.EMPLOYEE_ID, :OLD.FIRST_NAME, SYSDATE);
END;
/

CREATE TABLE SALARY_LOG (
    EMPLOYEE_ID NUMBER,
    OLD_SALARY NUMBER,
    NEW_SALARY NUMBER,
    CHANGE_TIME DATE
);

CREATE OR REPLACE TRIGGER trg_salary_update_log
AFTER UPDATE OF SALARY ON EMPLOYEES
FOR EACH ROW
BEGIN
    INSERT INTO SALARY_LOG
    VALUES (:OLD.EMPLOYEE_ID, :OLD.SALARY, :NEW.SALARY, SYSDATE);
END;
/

-- DDL)

CREATE TABLE AUDIT_LOG (
    TABLE_NAME VARCHAR2(50),
    CREATED_BY VARCHAR2(50),
    CREATED_AT DATE
);

CREATE OR REPLACE TRIGGER trg_table_create_log
AFTER CREATE ON DATABASE
BEGIN
    INSERT INTO AUDIT_LOG
    VALUES (ORA_DICT_OBJ_NAME, USER, SYSDATE);
END;
/

CREATE OR REPLACE TRIGGER trg_alter_restrict
BEFORE ALTER ON DATABASE
BEGIN
    IF ORA_DICT_OBJ_NAME = 'EMPLOYEES'
       AND (TO_CHAR(SYSDATE,'HH24') NOT BETWEEN 8 AND 18) THEN
        RAISE_APPLICATION_ERROR(-20002, 'ALTER not allowed after business hours');
    END IF;
END;
/

CREATE TABLE DROP_LOG (
    OBJECT_NAME VARCHAR2(50),
    USERNAME VARCHAR2(50),
    DROP_TIME DATE
);

CREATE OR REPLACE TRIGGER trg_drop_log
AFTER DROP ON DATABASE
BEGIN
    INSERT INTO DROP_LOG
    VALUES (ORA_DICT_OBJ_NAME, USER, SYSDATE);
END;
/

CREATE OR REPLACE TRIGGER trg_protect_audit_log
BEFORE DROP ON DATABASE
BEGIN
    IF ORA_DICT_OBJ_NAME = 'AUDIT_LOG' THEN
        RAISE_APPLICATION_ERROR(-20003, 'Cannot drop AUDIT_LOG table');
    END IF;
END;
/

-- SYSTEM TRIGGERS)

CREATE TABLE SYSTEM_LOGS (
    STATUS VARCHAR2(50),
    LOG_TIME DATE
);

CREATE OR REPLACE TRIGGER trg_db_startup
AFTER STARTUP ON DATABASE
BEGIN
    INSERT INTO SYSTEM_LOGS
    VALUES ('DATABASE STARTED', SYSDATE);
END;
/

CREATE TABLE FAILED_LOGINS (
    USERNAME VARCHAR2(50),
    ATTEMPT_TIME DATE
);

CREATE OR REPLACE TRIGGER trg_failed_login
AFTER SERVERERROR ON DATABASE
BEGIN
    INSERT INTO FAILED_LOGINS
    VALUES (USER, SYSDATE);
END;
/

CREATE TABLE USER_ACTIVITY_LOG (
    USERNAME VARCHAR2(50),
    ACTION VARCHAR2(20),
    LOG_TIME DATE
);

CREATE OR REPLACE TRIGGER trg_logoff
AFTER LOGOFF ON DATABASE
BEGIN
    INSERT INTO USER_ACTIVITY_LOG
    VALUES (USER, 'LOGOUT', SYSDATE);
END;
/

-- INSTEAD OF TRIGGERS)

CREATE VIEW EMP_DEPT_VIEW AS
SELECT e.EMPLOYEE_ID, e.FIRST_NAME, d.DEPARTMENT_NAME
FROM EMPLOYEES e
JOIN DEPARTMENTS d
ON e.DEPARTMENT_ID = d.DEPARTMENT_ID;

CREATE OR REPLACE TRIGGER trg_emp_dept_insert
INSTEAD OF INSERT ON EMP_DEPT_VIEW
FOR EACH ROW
BEGIN
    INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME)
    VALUES (:NEW.EMPLOYEE_ID, :NEW.FIRST_NAME);
END;
/

CREATE VIEW EMP_SAL_VIEW AS
SELECT EMPLOYEE_ID, SALARY
FROM EMPLOYEES;

CREATE OR REPLACE TRIGGER trg_salary_restrict_update
INSTEAD OF UPDATE ON EMP_SAL_VIEW
FOR EACH ROW
BEGIN
    IF :NEW.SALARY < :OLD.SALARY * 0.80 THEN
        RAISE_APPLICATION_ERROR(-20004, 'Salary cannot be reduced more than 20%');
    ELSE
        UPDATE EMPLOYEES
        SET SALARY = :NEW.SALARY
        WHERE EMPLOYEE_ID = :OLD.EMPLOYEE_ID;
    END IF;
END;
/

-- Q1)

-- a)
CREATE OR REPLACE TRIGGER trg_before_insert
BEFORE INSERT ON EMPLOYEES
BEGIN
    DBMS_OUTPUT.PUT_LINE('Record inserted');
END;
/

-- b)
CREATE OR REPLACE TRIGGER trg_before_update
BEFORE UPDATE ON EMPLOYEES
BEGIN
    DBMS_OUTPUT.PUT_LINE('User: ' || USER);
END;
/

-- c)
CREATE OR REPLACE TRIGGER trg_salary_check
BEFORE UPDATE OF SALARY ON EMPLOYEES
FOR EACH ROW
BEGIN
    IF :NEW.SALARY > 20000 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Salary cannot exceed 20000');
    END IF;
END;
/

-- d)
CREATE TABLE EMP_LOG (
    EMPLOYEE_ID NUMBER,
    FIRST_NAME VARCHAR2(50),
    DELETED_AT DATE
);

CREATE OR REPLACE TRIGGER trg_delete_log
BEFORE DELETE ON EMPLOYEES
FOR EACH ROW
BEGIN
    INSERT INTO EMP_LOG
    VALUES (:OLD.EMPLOYEE_ID, :OLD.FIRST_NAME, SYSDATE);
END;
/

-- Q2)

-- a)
CREATE OR REPLACE TRIGGER trg_transaction_audit
BEFORE INSERT ON TRANSACTIONS
FOR EACH ROW
BEGIN
    :NEW.CREATED_BY := USER;
    :NEW.CREATED_AT := SYSDATE;
END;
/

-- b)
CREATE TABLE DDL_LOG (
    USERNAME VARCHAR2(50),
    OBJECT_NAME VARCHAR2(50),
    CREATED_AT DATE
);

CREATE OR REPLACE TRIGGER trg_create_table
AFTER CREATE ON DATABASE
BEGIN
    INSERT INTO DDL_LOG
    VALUES (USER, ORA_DICT_OBJ_NAME, SYSDATE);
END;
/

-- c)
CREATE OR REPLACE TRIGGER trg_no_drop
BEFORE DROP ON DATABASE
BEGIN
    IF ORA_DICT_OBJ_NAME = 'EMPLOYEES' THEN
        RAISE_APPLICATION_ERROR(-20002, 'Cannot drop critical table');
    END IF;
END;
/

-- Q3)

CREATE TABLE LOGIN_LOG (
    USERNAME VARCHAR2(50),
    LOGIN_TIME DATE
);

CREATE OR REPLACE TRIGGER trg_logon
AFTER LOGON ON DATABASE
BEGIN
    INSERT INTO LOGIN_LOG
    VALUES (USER, SYSDATE);
END;
/

-- Q4) 

CREATE TABLE EMP_AUDIT (
    EMPLOYEE_ID NUMBER,
    OLD_SALARY NUMBER,
    NEW_SALARY NUMBER,
    ACTION_TYPE VARCHAR2(10),
    ACTION_DATE DATE
);

CREATE OR REPLACE TRIGGER trg_emp_audit
AFTER INSERT OR UPDATE OR DELETE ON EMPLOYEES
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO EMP_AUDIT
        VALUES (:NEW.EMPLOYEE_ID, NULL, :NEW.SALARY, 'INSERT', SYSDATE);

    ELSIF UPDATING THEN
        INSERT INTO EMP_AUDIT
        VALUES (:OLD.EMPLOYEE_ID, :OLD.SALARY, :NEW.SALARY, 'UPDATE', SYSDATE);

    ELSIF DELETING THEN
        INSERT INTO EMP_AUDIT
        VALUES (:OLD.EMPLOYEE_ID, :OLD.SALARY, NULL, 'DELETE', SYSDATE);
    END IF;
END;
/

-- Q5)

CREATE TABLE EMP_BACKUP AS SELECT * FROM EMPLOYEES WHERE 1=0;

CREATE TABLE SCHEMA_LOG (
    EVENT_TYPE VARCHAR2(20),
    OBJECT_NAME VARCHAR2(50),
    EVENT_TIME DATE
);

CREATE TABLE USER_ACTIVITY (
    USERNAME VARCHAR2(50),
    ACTION VARCHAR2(10),
    TIME DATE
);

CREATE VIEW EMP_VIEW_SIMPLE AS
SELECT EMPLOYEE_ID, FIRST_NAME FROM EMPLOYEES;

CREATE OR REPLACE TRIGGER trg_backup
AFTER INSERT OR UPDATE OR DELETE ON EMPLOYEES
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO EMP_BACKUP VALUES (:NEW.EMPLOYEE_ID, :NEW.FIRST_NAME, :NEW.SALARY);

    ELSIF UPDATING THEN
        UPDATE EMP_BACKUP
        SET SALARY = :NEW.SALARY
        WHERE EMPLOYEE_ID = :OLD.EMPLOYEE_ID;

    ELSIF DELETING THEN
        DELETE FROM EMP_BACKUP
        WHERE EMPLOYEE_ID = :OLD.EMPLOYEE_ID;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_schema
AFTER CREATE OR ALTER OR DROP ON DATABASE
BEGIN
    INSERT INTO SCHEMA_LOG
    VALUES (ORA_SYSEVENT, ORA_DICT_OBJ_NAME, SYSDATE);
END;
/

CREATE OR REPLACE TRIGGER trg_logon_logoff
AFTER LOGON OR LOGOFF ON DATABASE
BEGIN
    INSERT INTO USER_ACTIVITY
    VALUES (USER, ORA_SYSEVENT, SYSDATE);
END;
/

CREATE OR REPLACE TRIGGER trg_instead_view
INSTEAD OF INSERT ON EMP_VIEW_SIMPLE
FOR EACH ROW
BEGIN
    INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME)
    VALUES (:NEW.EMPLOYEE_ID, :NEW.FIRST_NAME);
END;
/

-- Q6)

CREATE TABLE EMP_FULL_AUDIT (
    EMPLOYEE_ID NUMBER,
    OLD_SALARY NUMBER,
    NEW_SALARY NUMBER,
    ACTION_TYPE VARCHAR2(10),
    USERNAME VARCHAR2(50),
    ACTION_TIME DATE
);

CREATE OR REPLACE TRIGGER trg_full_audit
AFTER INSERT OR UPDATE OR DELETE ON EMPLOYEES
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO EMP_FULL_AUDIT
        VALUES (:NEW.EMPLOYEE_ID, NULL, :NEW.SALARY, 'INSERT', USER, SYSDATE);

    ELSIF UPDATING THEN
        INSERT INTO EMP_FULL_AUDIT
        VALUES (:OLD.EMPLOYEE_ID, :OLD.SALARY, :NEW.SALARY, 'UPDATE', USER, SYSDATE);

    ELSIF DELETING THEN
        INSERT INTO EMP_FULL_AUDIT
        VALUES (:OLD.EMPLOYEE_ID, :OLD.SALARY, NULL, 'DELETE', USER, SYSDATE);
    END IF;
END;
/

-- Q7)

CREATE OR REPLACE TRIGGER trg_backup
AFTER INSERT OR UPDATE OR DELETE ON EMPLOYEES
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO EMP_BACKUP VALUES (:NEW.EMPLOYEE_ID, :NEW.FIRST_NAME, :NEW.SALARY);
    ELSIF UPDATING THEN
        UPDATE EMP_BACKUP
        SET SALARY = :NEW.SALARY
        WHERE EMPLOYEE_ID = :OLD.EMPLOYEE_ID;
    ELSIF DELETING THEN
        DELETE FROM EMP_BACKUP
        WHERE EMPLOYEE_ID = :OLD.EMPLOYEE_ID;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_schema
AFTER CREATE OR ALTER OR DROP ON DATABASE
BEGIN
    INSERT INTO SCHEMA_LOG
    VALUES (ORA_SYSEVENT, ORA_DICT_OBJ_NAME, SYSDATE);
END;
/

CREATE OR REPLACE TRIGGER trg_log
AFTER LOGON OR LOGOFF ON DATABASE
BEGIN
    INSERT INTO USER_LOG
    VALUES (USER, ORA_SYSEVENT, SYSDATE);
END;
/

CREATE OR REPLACE TRIGGER trg_view
INSTEAD OF INSERT ON EMP_VIEW
FOR EACH ROW
BEGIN
    INSERT INTO EMPLOYEES
    VALUES (:NEW.EMPLOYEE_ID, :NEW.FIRST_NAME, :NEW.SALARY);
END;
/

-- Lab 8 - END
